# Generated by Django 6.0.6 on 2026-06-05 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers only'), ('community', 'Community only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
