# Generated by Django 6.0.6 on 2026-06-06 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_story_liked_by_story_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_reshare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_share_to_story',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers only'), ('community_only', 'Community only'), ('private', 'Private')], default='public', max_length=16),
        ),
        migrations.CreateModel(
            name='PostReshare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True)),
                ('visibility', models.CharField(default='public', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reshares', to='posts.post')),
                ('reshared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reshares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('original_post', 'reshared_by')},
            },
        ),
    ]
