# Generated by Django 6.0.6 on 2026-06-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_allow_reshare_post_allow_share_to_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_shares', to='posts.post'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(default='image', max_length=16),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
