# Generated by Django 6.0.6 on 2026-06-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_project_category_project_cover_image_and_more'),
        ('posts', '0005_story_original_post_story_story_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.community'),
        ),
    ]
