# Generated by Django 6.0.6 on 2026-06-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='UK', max_length=60)),
                ('careers_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('sponsorship_confidence', models.CharField(choices=[('confirmed', 'Confirmed'), ('likely', 'Likely'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='UK', max_length=60),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
