# Generated by Django 6.0.5 on 2026-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('tech', 'Tech Team'), ('social', 'Social Media / Marketing'), ('lead', 'Team Lead')], default='tech', max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
