# Generated by Django 6.0.5 on 2026-06-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0006_communityevent_communityresource'),
        ('jobs', '0004_seed_intl_jobs'),
        ('study_match', '0005_citystudydata_externaljob_rawadzunajobsdata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='clips/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='clips/thumbs/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('uk_life', 'UK Life'), ('jobs', 'Jobs'), ('accommodation', 'Accommodation'), ('study', 'Study'), ('visa', 'Visa'), ('career', 'Career'), ('projects', 'Projects'), ('city_guides', 'City Guides'), ('community', 'Community')], db_index=True, default='uk_life', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers only'), ('community_only', 'Community only'), ('private', 'Private')], default='public', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_city_slug', models.SlugField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='ready', max_length=12)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='community.community')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_clips', to=settings.AUTH_USER_MODEL)),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='study_match.course')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='jobs.job')),
                ('related_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='study_match.university')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_clips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClipComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clips.clip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clips.clip')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['category', '-created_at'], name='clips_clip_categor_9a8562_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clipreport',
            unique_together={('clip', 'reporter')},
        ),
    ]
