# Generated by Django 6.0.5 on 2026-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('uk_status', models.CharField(choices=[('student', 'Student'), ('psw', 'Post Study Work Visa (PSW)'), ('employed', 'Currently Employed'), ('other', 'Other')], max_length=20)),
                ('professional_field', models.CharField(choices=[('software', 'Software Development'), ('data_ai', 'Data / AI / ML'), ('project_management', 'Project Management'), ('non_tech', 'Non-tech'), ('other', 'Other')], max_length=30)),
                ('experience', models.CharField(choices=[('0-1', '0–1 years'), ('2-3', '2–3 years'), ('4-6', '4–6 years'), ('7+', '7+ years')], max_length=10)),
                ('looking_for', models.CharField(blank=True, max_length=200)),
                ('biggest_challenge', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
