# Generated by Django 6.0.6 on 2026-06-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_seed_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_app', 'Web App'), ('mobile_app', 'Mobile App'), ('ai_ml', 'AI/ML'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('full_stack', 'Full Stack'), ('ui_ux', 'UI/UX'), ('startup_idea', 'Startup Idea'), ('university_project', 'University Project'), ('open_source', 'Open Source'), ('other', 'Other')], default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='looking_for_collaborators',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='roles_needed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('looking_for_team', 'Looking for Team'), ('open_to_collab', 'Open to Collaboration')], default='idea', max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers only'), ('community', 'Community only'), ('private', 'Private')], default='public', max_length=12),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_shots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='community.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
