# Generated by Django 6.0.5 on 2026-06-01 17:11

import accounts.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('university', models.CharField(blank=True, max_length=160)),
                ('course', models.CharField(blank=True, max_length=160)),
                ('graduation_date', models.CharField(blank=True, max_length=20)),
                ('intake_year', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, choices=[('student', 'Current Student'), ('psw', 'Post Study Work Visa'), ('graduate', 'Recent Graduate'), ('employed', 'Employed'), ('other', 'Other')], max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('looking_for', models.JSONField(blank=True, default=list)),
                ('career_goals', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, choices=[('student', 'Student'), ('alumni', 'Alumni'), ('recruiter', 'Recruiter')], max_length=20)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
