# Generated by Django 6.0.5 on 2026-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_visit_user_longest_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='display_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hiring_for',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='open_to_networking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='open_to_referrals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='study_level',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('professional', 'Working Professional'), ('recruiter', 'Recruiter')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
