# Generated by Django 6.0.6 on 2026-06-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_company_user_display_company_user_hiring_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
