# Generated by Django 6.0.6 on 2026-06-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activityday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='content_niche',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='creator_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='destination_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='newcomer_needs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='open_to_mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='target_role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('professional', 'Working Professional'), ('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter'), ('creator', 'Creator'), ('newcomer', 'New to UK')], default='student', max_length=20),
        ),
    ]
