# Generated by Django 6.0.6 on 2026-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_arrival_date_user_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_messages_from',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('connections', 'Connections'), ('no_one', 'No one')], default='everyone', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_post_reshare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_story_sharing',
            field=models.BooleanField(default=True),
        ),
    ]
