# Generated by Django 6.0.5 on 2026-06-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_email_verified_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('both', 'Both')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('register', 'Register'), ('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('logout_all', 'Logout all devices'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('email_verified', 'Email verified'), ('email_verification_sent', 'Verification email sent'), ('google_login_success', 'Google login success'), ('google_login_failed', 'Google login failed'), ('rate_limited', 'Rate limited'), ('phone_added', 'Phone number added'), ('whatsapp_changed', 'WhatsApp opt-in changed'), ('username_changed', 'Username changed'), ('password_changed', 'Password changed')], max_length=40),
        ),
    ]
