# Generated by Django 6.0.5 on 2026-06-07 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=120)),
                ('source_url', models.URLField()),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedStudyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('country', 'Country'), ('course', 'Course'), ('university', 'University'), ('city', 'City'), ('scholarship', 'Scholarship'), ('accommodation', 'Accommodation')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('university', models.CharField(blank=True, max_length=160)),
                ('course', models.CharField(blank=True, max_length=160)),
                ('fee', models.CharField(blank=True, max_length=80)),
                ('intake', models.CharField(blank=True, max_length=40)),
                ('entry_requirements', models.TextField(blank=True)),
                ('english_requirement', models.CharField(blank=True, max_length=120)),
                ('official_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('shortlisted', 'Shortlisted'), ('applied', 'Applied'), ('offer_received', 'Offer received'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('visa_stage', 'Visa stage'), ('accommodation_stage', 'Accommodation stage')], default='researching', max_length=24)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_study_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_country', models.CharField(blank=True, max_length=80)),
                ('education_level', models.CharField(blank=True, max_length=80)),
                ('current_qualification', models.CharField(blank=True, max_length=160)),
                ('marks_or_cgpa', models.CharField(blank=True, max_length=40)),
                ('work_experience', models.CharField(blank=True, max_length=80)),
                ('desired_study_level', models.CharField(blank=True, max_length=40)),
                ('subject_interest', models.CharField(blank=True, max_length=120)),
                ('career_goal', models.CharField(blank=True, max_length=160)),
                ('preferred_intake', models.CharField(blank=True, max_length=40)),
                ('preferred_countries', models.JSONField(blank=True, default=list)),
                ('tuition_budget', models.CharField(blank=True, max_length=40)),
                ('living_budget', models.CharField(blank=True, max_length=40)),
                ('needs_scholarship', models.BooleanField(default=False)),
                ('needs_part_time_work', models.BooleanField(default=False)),
                ('english_test_type', models.CharField(blank=True, max_length=40)),
                ('english_test_score', models.CharField(blank=True, max_length=40)),
                ('passport_status', models.BooleanField(default=False)),
                ('document_status', models.BooleanField(default=False)),
                ('priorities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_summary', models.TextField(blank=True)),
                ('country_scores', models.JSONField(blank=True, default=list)),
                ('course_recommendations', models.JSONField(blank=True, default=list)),
                ('university_recommendations', models.JSONField(blank=True, default=list)),
                ('city_recommendations', models.JSONField(blank=True, default=list)),
                ('career_market_insights', models.JSONField(blank=True, default=dict)),
                ('visa_cost_checklist', models.JSONField(blank=True, default=dict)),
                ('action_plan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_results', to=settings.AUTH_USER_MODEL)),
                ('study_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='study_match.studyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('done', 'Done')], default='todo', max_length=8)),
                ('linked_plan_task_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='study_match.savedstudyoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
