# Generated by Django 6.0.5 on 2026-06-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstudyoption',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedstudyoption',
            name='match_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedstudyoption',
            name='source_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='savedstudyoption',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
