# Generated by Django 6.0.5 on 2026-06-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_match', '0002_savedstudyoption_last_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=120, unique=True)),
                ('source_type', models.CharField(blank=True, max_length=60)),
                ('source_url', models.URLField(blank=True)),
                ('update_frequency', models.CharField(blank=True, max_length=60)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='idle', max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('inserted_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=40)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.SlugField(max_length=120, unique=True)),
                ('university_name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('region', models.CharField(blank=True, db_index=True, max_length=120)),
                ('country', models.CharField(default='United Kingdom', max_length=80)),
                ('website_url', models.URLField(blank=True)),
                ('ukprn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('university_type', models.CharField(blank=True, max_length=80)),
                ('is_russell_group', models.BooleanField(default=False)),
                ('ukvi_sponsor_status', models.CharField(choices=[('licensed', 'Licensed sponsor'), ('not_listed', 'Not on register'), ('unknown', 'Unknown / not checked')], default='unknown', max_length=16)),
                ('sponsor_rating', models.CharField(blank=True, max_length=40)),
                ('international_office_url', models.URLField(blank=True)),
                ('accommodation_url', models.URLField(blank=True)),
                ('scholarship_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('data_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=8)),
                ('needs_verification', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['university_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.SlugField(max_length=160, unique=True)),
                ('university_name', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(db_index=True, max_length=240)),
                ('degree_level', models.CharField(blank=True, db_index=True, max_length=60)),
                ('subject_area', models.CharField(blank=True, db_index=True, max_length=120)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('study_mode', models.CharField(blank=True, max_length=60)),
                ('intake_months', models.JSONField(blank=True, default=list)),
                ('international_fee_gbp', models.PositiveIntegerField(blank=True, null=True)),
                ('international_fee_text', models.CharField(blank=True, max_length=120)),
                ('home_fee_gbp', models.PositiveIntegerField(blank=True, null=True)),
                ('application_fee_gbp', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_requirements', models.TextField(blank=True)),
                ('english_language_requirement', models.CharField(blank=True, max_length=200)),
                ('ielts_overall', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ielts_per_component', models.CharField(blank=True, max_length=120)),
                ('pte_requirement', models.CharField(blank=True, max_length=80)),
                ('work_placement_available', models.BooleanField(blank=True, null=True)),
                ('scholarship_info', models.TextField(blank=True)),
                ('campus_location', models.CharField(blank=True, max_length=160)),
                ('course_url', models.URLField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('fee_verified', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('data_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=8)),
                ('needs_verification', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='study_match.university')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
    ]
