# Generated by Django 6.0.5 on 2026-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_match', '0003_datasource_synclog_university_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStudyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('study_score', models.PositiveIntegerField(default=0)),
                ('work_score', models.PositiveIntegerField(default=0)),
                ('budget_score', models.PositiveIntegerField(default=0)),
                ('visa_score', models.PositiveIntegerField(default=0)),
                ('language_score', models.PositiveIntegerField(default=0)),
                ('ranking_score', models.PositiveIntegerField(default=0)),
                ('student_life_score', models.PositiveIntegerField(default=0)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('best_for_subjects', models.JSONField(blank=True, default=list)),
                ('popular_cities', models.JSONField(blank=True, default=list)),
                ('tuition_band', models.CharField(blank=True, max_length=20)),
                ('living_cost_band', models.CharField(blank=True, max_length=20)),
                ('post_study_work_summary', models.CharField(blank=True, max_length=200)),
                ('part_time_work_summary', models.CharField(blank=True, max_length=200)),
                ('language_notes', models.CharField(blank=True, max_length=200)),
                ('risk_notes', models.TextField(blank=True)),
                ('weekly_update_summary', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('update_frequency', models.CharField(default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='StudyDataImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
