# Generated by Django 6.0.5 on 2026-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_match', '0004_countrystudyinsight_studydataimportrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStudyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=120)),
                ('country', models.CharField(default='United Kingdom', max_length=80)),
                ('cost_level', models.CharField(blank=True, max_length=20)),
                ('rent_level', models.CharField(blank=True, max_length=20)),
                ('monthly_living_cost_band', models.CharField(blank=True, max_length=40)),
                ('average_rent_band', models.CharField(blank=True, max_length=40)),
                ('salary_signal', models.CharField(blank=True, max_length=20)),
                ('employment_signal', models.CharField(blank=True, max_length=20)),
                ('part_time_job_signal', models.CharField(blank=True, max_length=20)),
                ('graduate_job_market_signal', models.CharField(blank=True, max_length=20)),
                ('safety_signal', models.CharField(blank=True, max_length=20)),
                ('student_life_signal', models.CharField(blank=True, max_length=20)),
                ('international_community_signal', models.CharField(blank=True, max_length=20)),
                ('accommodation_difficulty', models.CharField(blank=True, max_length=20)),
                ('transport_signal', models.CharField(blank=True, max_length=20)),
                ('main_industries', models.JSONField(blank=True, default=list)),
                ('best_for_subjects', models.JSONField(blank=True, default=list)),
                ('best_for_career_areas', models.JSONField(blank=True, default=list)),
                ('top_universities', models.JSONField(blank=True, default=list)),
                ('related_communities', models.JSONField(blank=True, default=list)),
                ('city_summary', models.TextField(blank=True)),
                ('why_choose_this_city', models.TextField(blank=True)),
                ('what_to_be_careful_about', models.TextField(blank=True)),
                ('cost_value', models.PositiveIntegerField(default=3)),
                ('rent_value', models.PositiveIntegerField(default=3)),
                ('part_time_value', models.PositiveIntegerField(default=3)),
                ('grad_value', models.PositiveIntegerField(default=3)),
                ('student_life_value', models.PositiveIntegerField(default=3)),
                ('community_value', models.PositiveIntegerField(default=3)),
                ('accommodation_value', models.PositiveIntegerField(default=3)),
                ('overall_city_score', models.PositiveIntegerField(default=0)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('data_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_city_score', 'city'],
            },
        ),
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('country', models.CharField(default='United Kingdom', max_length=80)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('apply_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RawAdzunaJobsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawGovStudentSponsorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawHesaProviderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawNomisLabourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawONSRentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawPoliceSafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
                'abstract': False,
            },
        ),
    ]
