# Generated by Django 6.0.6 on 2026-06-05 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_initiator_conversation_is_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('community', 'Community'), ('broadcast', 'Broadcast'), ('ai', 'AI Assistant')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
