# Generated by Django 6.0.6 on 2026-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_file_message_file_name_message_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('gif', 'GIF'), ('doodle', 'Doodle'), ('view_once', 'View once'), ('document', 'Document'), ('location', 'Location'), ('shared_post', 'Shared post'), ('shared_profile', 'Shared profile'), ('shared_job', 'Shared job'), ('shared_community', 'Shared community')], default='text', max_length=20),
        ),
    ]
