# Generated by Django 6.0.6 on 2026-06-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_created_by'),
        ('messaging', '0006_message_shared_id_message_shared_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='community.community'),
        ),
    ]
