# Generated by Django 6.0.6 on 2026-06-06 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_conversation_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='muted_by',
            field=models.ManyToManyField(blank=True, related_name='muted_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
