# Generated by Django 6.0.5 on 2026-06-07 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('text', 'Text')], default='website', max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_text', models.TextField(blank=True)),
                ('source_image', models.URLField(blank=True, max_length=1000)),
                ('source_video', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, max_length=1000)),
                ('destination_type', models.CharField(blank=True, choices=[('post', 'Post'), ('story', 'Story'), ('community_resource', 'Community resource'), ('message', 'Message'), ('plan', 'Plan task'), ('job_application', 'Job application'), ('saved', 'Saved only')], max_length=20)),
                ('destination_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('imported', 'Imported'), ('removed', 'Removed')], default='imported', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
