"""Direct messaging: 1-on-1 conversations and messages."""
from django.conf import settings
from django.db import models


class Conversation(models.Model):
    class Kind(models.TextChoices):
        DIRECT = "direct", "Direct"
        GROUP = "group", "Group"
        COMMUNITY = "community", "Community"
        BROADCAST = "broadcast", "Broadcast"
        AI = "ai", "AI Assistant"

    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="conversations")
    kind = models.CharField(max_length=20, choices=Kind.choices, default=Kind.DIRECT)
    title = models.CharField(max_length=120, blank=True)
    image = models.ImageField(upload_to="chat/", blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              null=True, blank=True, related_name="owned_conversations")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_request = models.BooleanField(default=False)  # pending message request
    initiator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                  null=True, blank=True, related_name="initiated_conversations")

    class Meta:
        ordering = ["-updated_at"]

    @classmethod
    def between(cls, user_a, user_b):
        """Get or create the 1-on-1 conversation between two users.
        Race-safe: always returns the oldest existing conversation, and
        cleans up any duplicate empty conversations created by a race."""
        from django.db import transaction

        with transaction.atomic():
            existing = list(
                cls.objects.filter(participants=user_a)
                           .filter(participants=user_b)
                           .order_by("id")
            )
            if existing:
                keeper = existing[0]
                # Remove duplicate empty conversations from past races
                for dup in existing[1:]:
                    if not dup.messages.exists():
                        dup.delete()
                return keeper
            convo = cls.objects.create()
            convo.participants.add(user_a, user_b)
            return convo

    def __str__(self):
        return f"Conversation #{self.id}"


class Message(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField()
    is_ai = models.BooleanField(default=False)  # reply generated by the AI assistant
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        who = "AI" if self.is_ai else (self.sender.full_name if self.sender else "?")
        return f"{who}: {self.body[:30]}"
