"""Direct messaging: 1-on-1 conversations and messages."""
from django.conf import settings
from django.db import models


class Conversation(models.Model):
    class Kind(models.TextChoices):
        DIRECT = "direct", "Direct"
        GROUP = "group", "Group"
        COMMUNITY = "community", "Community"
        BROADCAST = "broadcast", "Broadcast"
        AI = "ai", "AI Assistant"

    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="conversations")
    kind = models.CharField(max_length=20, choices=Kind.choices, default=Kind.DIRECT)
    title = models.CharField(max_length=120, blank=True)
    image = models.ImageField(upload_to="chat/", blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              null=True, blank=True, related_name="owned_conversations")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_request = models.BooleanField(default=False)  # pending message request
    initiator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                  null=True, blank=True, related_name="initiated_conversations")

    class Meta:
        ordering = ["-updated_at"]

    @classmethod
    def between(cls, user_a, user_b):
        """Get or create the 1-on-1 conversation between two users.
        Race-safe: always returns the oldest existing conversation, and
        cleans up any duplicate empty conversations created by a race."""
        from django.db import transaction

        with transaction.atomic():
            existing = list(
                cls.objects.filter(participants=user_a)
                           .filter(participants=user_b)
                           .order_by("id")
            )
            if existing:
                keeper = existing[0]
                # Remove duplicate empty conversations from past races
                for dup in existing[1:]:
                    if not dup.messages.exists():
                        dup.delete()
                return keeper
            convo = cls.objects.create()
            convo.participants.add(user_a, user_b)
            return convo

    def __str__(self):
        return f"Conversation #{self.id}"


class Message(models.Model):
    class Kind(models.TextChoices):
        TEXT = "text", "Text"
        IMAGE = "image", "Image"
        GIF = "gif", "GIF"
        DOODLE = "doodle", "Doodle"
        VIEW_ONCE = "view_once", "View once"
        DOCUMENT = "document", "Document"
        LOCATION = "location", "Location"
        SHARED_POST = "shared_post", "Shared post"
        SHARED_PROFILE = "shared_profile", "Shared profile"
        SHARED_JOB = "shared_job", "Shared job"
        SHARED_COMMUNITY = "shared_community", "Shared community"

    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField(blank=True)
    kind = models.CharField(max_length=20, choices=Kind.choices, default=Kind.TEXT)
    image = models.ImageField(upload_to="messages/", blank=True, null=True)
    file = models.FileField(upload_to="message_files/", blank=True, null=True)  # documents
    file_name = models.CharField(max_length=200, blank=True)
    gif_url = models.URLField(blank=True)
    lat = models.FloatField(null=True, blank=True)   # location
    lng = models.FloatField(null=True, blank=True)
    # shared cards (post/profile/job/community): id of the shared object + a small preview payload
    shared_id = models.CharField(max_length=64, blank=True)
    shared_payload = models.JSONField(null=True, blank=True)
    viewed_at = models.DateTimeField(null=True, blank=True)  # for view-once: when recipient opened it
    is_ai = models.BooleanField(default=False)  # reply generated by the AI assistant
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    @property
    def is_view_once_consumed(self):
        return self.kind == self.Kind.VIEW_ONCE and self.viewed_at is not None

    def __str__(self):
        who = "AI" if self.is_ai else (self.sender.full_name if self.sender else "?")
        label = self.body[:30] if self.body else f"[{self.kind}]"
        return f"{who}: {label}"


class MessageReaction(models.Model):
    """One emoji reaction per user per message (Instagram-style)."""
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="reactions")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    emoji = models.CharField(max_length=8)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("message", "user")

    def __str__(self):
        return f"{self.emoji} by {self.user_id} on msg {self.message_id}"
