# Generated by Django 6.0.6 on 2026-06-06 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0005_seed_starter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('extracted_text', models.TextField(blank=True)),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('job_match_score', models.PositiveIntegerField(blank=True, null=True)),
                ('section_scores', models.JSONField(blank=True, default=dict)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('passed_checks', models.JSONField(blank=True, default=list)),
                ('failed_checks', models.JSONField(blank=True, default=list)),
                ('improvement_checks', models.JSONField(blank=True, default=list)),
                ('top_fixes', models.JSONField(blank=True, default=list)),
                ('recommended_roles', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('role_title', models.CharField(blank=True, max_length=160)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_preps', to='scheduler.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('role_title', models.CharField(blank=True, max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_linkedin', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('follow_up', 'Follow-up needed'), ('referred', 'Referred'), ('declined', 'Declined'), ('no_response', 'No response')], default='not_requested', max_length=16)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_asks', to=settings.AUTH_USER_MODEL)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='scheduler.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
