# Generated by Django 6.0.6 on 2026-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('follow', 'started following you'), ('request', 'requested to follow you'), ('message', 'sent you a message'), ('follow_accepted', 'accepted your follow request'), ('story_like', 'liked your story'), ('story_reply', 'replied to your story'), ('story_share', 'shared your story'), ('streak', 'reached a streak milestone'), ('message_reaction', 'reacted to your message'), ('view_once_opened', 'opened your photo')], max_length=20),
        ),
    ]
