# Generated by Django 6.0.6 on 2026-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_conversation_id_notification_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='community_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='reshare_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
