# Generated by Django 6.0.6 on 2026-06-06 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_community_id_notification_reshare_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('follow', 'started following you'), ('request', 'requested to follow you'), ('message', 'sent you a message'), ('follow_accepted', 'accepted your follow request'), ('story_like', 'liked your story'), ('story_reply', 'replied to your story'), ('story_share', 'shared your story'), ('streak', 'reached a streak milestone'), ('message_reaction', 'reacted to your message'), ('view_once_opened', 'opened your photo'), ('reminder', 'reminder')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('referral_follow_up', 'Referral follow-up'), ('application_follow_up', 'Application follow-up'), ('interview', 'Interview reminder'), ('custom', 'Custom')], default='custom', max_length=24)),
                ('text', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField()),
                ('fired', models.BooleanField(default=False)),
                ('target_type', models.CharField(blank=True, max_length=24)),
                ('referral_id', models.CharField(blank=True, max_length=64)),
                ('job_id', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
    ]
