# Generated by Django 6.0.5 on 2026-06-03 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opportunity', 'Opportunity'), ('event', 'Community Event')], default='opportunity', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('org', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('interview', 'Interview'), ('job_deadline', 'Job Deadline'), ('accommodation', 'Accommodation'), ('visa', 'Visa'), ('university', 'University'), ('projects', 'Projects'), ('networking', 'Networking'), ('career_fair', 'Career Fair'), ('community_event', 'Community Event'), ('personal_goal', 'Personal Goal'), ('certification', 'Certification'), ('referral_followup', 'Referral Follow-up'), ('other', 'Other')], default='other', max_length=24)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('job', 'Job'), ('event', 'Community Event'), ('referral', 'Referral'), ('project', 'Project')], default='manual', max_length=12)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('target', models.PositiveIntegerField(default=1)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
