# Generated by Django 6.0.6 on 2026-06-05 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('scheduler', '0002_seed_opportunities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygoal',
            name='kind',
            field=models.CharField(choices=[('jobs', 'Job Applications'), ('networking', 'Networking'), ('custom', 'Custom')], default='custom', max_length=12),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=12),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('role_title', models.CharField(blank=True, max_length=160)),
                ('job_link', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('response', 'Response received'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer'), ('follow_up', 'Follow-up needed')], default='saved', max_length=12)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='scheduler.weeklygoal')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
