# Generated by Django 6.0.6 on 2026-06-05 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_weeklygoal_kind_weeklygoal_status_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklygoal',
            name='week_start',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
